### ISSUE TITLE
Documentation clairification 

### ISSUE THREAD

**Issue by Motophan** [robbertkl/docker-ipv6nat#66]
`/etc/docker/daemon.json`
```
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00:dead:beef::/48"
}
```
Is this what you mean by "make sure your Docker daemon is started with --ipv6 and specifies a ULA range with --fixed-cidr-v6 (e.g. --fixed-cidr-v6 fd00:dead:beef::/48)"

My docker daemon on debian 10 with `docker network inspect bridge` showed
```
    {
        "Name": "bridge",
        "Id": "2e95b4c4edbc6c298bf3eebc436b0be6b5ee9681da58dddd3c4b7721bb764295",
        "Created": "2020-12-28T03:11:11.061086556Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
...

```
If so, could you make an example container compose stanza to bring up a your container and a nginx container with dual stack?

```
version: '2.4'

networks:
  mynetwork:
    driver: bridge

services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/username/nginx/:/etc/nginx/
    ports:
      - 80:80
      - 443:443
  ipv6nat: 
    image: robbertkl/ipv6nat:latest
    container_name: ipv6nat
    privileged: True
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
```

My issue with compose is

1- docker-compose down removes the user defined network
2- unsure how to instruct compose to create the network `docker network create --ipv6 --subnet fd00:dead:beef::/48 mynetwork` 

notes: my setup wont show ipv6 enabled for bridge for some reason. I dont know what to do to trigger it. I would like to have a user defined bridge as ipv6 and have that bridge created in compose.

Assuming my public IP (I have a /64, but my adapter assigns `2001:0db8:85a3:0000:0000:8a2e:0370:7334` (example address) as my host's IP. I want to put that in the DNS as a AAAA record and I want containers to be able to open ports on this IP address, specifically nginx container on port 80,443.
