### ISSUE TITLE
Prefer ipv6 over ipv4

### ISSUE THREAD

**Issue by guysoft** [robbertkl/docker-ipv6nat#78]
Hey,
Is there a way to set that Ipv6 would be preferred to ipv4?

If I bring up a container I get that unless spefied (or ipv6-only site) ipv4 is used:
```
ping www.google.com
PING www.google.com (142.250.184.196): 56 data bytes
64 bytes from 142.250.184.196: seq=0 ttl=110 time=69.688 ms
```

Only if I force ipv6 it uses it:

```
/ # ping -6 www.google.com
PING www.google.com (2a00:1450:4001:80f::2004): 56 data bytes
64 bytes from 2a00:1450:4001:80f::2004: seq=0 ttl=116 time=59.688 ms
```

Its like this for every container I tried.
docker-compose:

```yaml
  ipv6:
    image: robbertkl/ipv6nat
    container_name: ipv6nat
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
networks:
  default:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
       - subnet: fd00:0000:0000:1::/64
```

/etc/docker/daemon.json:

```json
 {
          "ipv6": true,
          "fixed-cidr-v6": "fd00::/80"
}
```

```
$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:19 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:40:35 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
Thanks
