### ISSUE TITLE
Couldn't load target `DOCKER'

### ISSUE THREAD

**Issue by MeCJay12** [robbertkl/docker-ipv6nat#82]
Hello! I'm running this container in a WSL2 Ubuntu VM. I'm getting the following error:

```
2025/03/18 19:37:40 running [/sbin/iptables -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load target `DOCKER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```

docker compose to create it
```
services:
  ipv6nat:
    restart: always
    network_mode: host
    container_name: v6NAT
    privileged: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
    image: robbertkl/ipv6nat
networks: {}
```

daemon config file
```
cat /etc/docker/daemon.json
{
    "fixed-cidr-v6": "fd00::/64",
    "ipv6": true,
    "log-driver": "local",
    "log-opts": {
        "max-size": "10m"
    },
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}
```

docker version and OS
```
docker --version
Docker version 26.1.3, build 26.1.3-0ubuntu1~24.04.1
```
